# Generated by Django 2.1.1 on 2018-09-08 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_auto_20180908_2315'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='keyword',
            new_name='keywords',
        ),
    ]
