# Generated by Django 2.1.1 on 2018-09-12 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0004_auto_20180913_0144'),
    ]

    operations = [
        migrations.RenameField(
            model_name='record',
            old_name='title',
            new_name='phase',
        ),
    ]
